// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/mobile/submit","id":"1"},"2":{"path":"/admin/login","id":"2"},"3":{"path":"/admin","id":"3"},"4":{"path":"/admin/dashboard","parentId":"3","id":"4"},"5":{"path":"/admin/requests","parentId":"3","id":"5"},"6":{"path":"/admin/products","parentId":"3","id":"6"},"7":{"path":"/admin/settings","parentId":"3","id":"7"},"8":{"redirect":"/admin/dashboard","parentId":"3","id":"8"},"9":{"path":"/","redirect":"/mobile/submit","id":"9"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__mobile__submit__index" */'@/pages/mobile/submit/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__admin__login__index" */'@/pages/admin/login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__admin__dashboard__index" */'@/pages/admin/dashboard/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__admin__requests__index" */'@/pages/admin/requests/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__admin__products__index" */'@/pages/admin/products/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__admin__settings__index" */'@/pages/admin/settings/index.tsx')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import('./EmptyRoute')),
},
  };
}
